### ISSUE TITLE
Let user run commands before and after build process.

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Niraj-Kamdar/manylinux-wheel-builder#6]
Automatically run pre_build.sh if exists before building wheels and post_build.sh after building wheels.
- [ ] Add support for pre_build.sh
- [ ] Add support for post_build.sh

**Comment by mozman** [comment]
Hi!

Thank you for your work and a pre_build.sh would be a nice feature. I had to fork your repository to add a `python -m pip install cython`.

A similar build system (https://github.com/marketplace/actions/python-wheels-manylinux-build) can pass options in the yaml file, I would just need the `build-requirements`:

```
uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
with:
  python-versions: 'cp36-cp36m cp37-cp37m'
  build-requirements: 'cython numpy'
  system-packages: 'lrzip-devel zlib-devel'
  pre-build-command: 'sh pre-build-script.sh'
  package-path: 'my_project'
  pip-wheel-args: '-w ./dist --no-deps'

```

Best regards,
Manfred
