### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by PaNDa2code** [Niraj-Kamdar/manylinux-wheel-builder#9]
Hello,

I am relatively new to Python packaging and am currently facing an issue with the GitHub Actions workflow for deploying manylinux wheels using the provided action file in the documentation.

**Action File:**
```yaml
name: pypi manylinux wheel deployer
on:
  push:
    - "v*"
jobs:
  Linux-build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: build and upload manylinux wheels
        uses: Niraj-Kamdar/manylinux-wheel-builder@master
```

**Issue:**
When attempting to release a new version, I encounter the following error during the job run:

```bash
 > [3/3] RUN /opt/python/cp37-cp37m/bin/pip install twine:
  6.725 error: subprocess-exited-with-error
  6.725 
  6.725 × pip subprocess to install build dependencies did not run successfully.
  6.725 │ exit code: 1
  6.725 ╰─> See above for output.
  6.725 
  6.725 note: This error originates from a subprocess, and is likely not a problem with pip.
  6.731 
  Notice: 6.731 [notice] A new release of pip available: 22.2.2 -> 23.3.2
  Notice: 6.731 [notice] To update, run: /opt/_internal/cpython-3.7.13/bin/python -m pip install --upgrade pip
  ------
  Dockerfile:3
  --------------------
     1 |     FROM quay.io/pypa/manylinux2010_x86_64
     2 |     COPY entrypoint.py /entrypoint.py
     3 | >>> RUN /opt/python/cp37-cp37m/bin/pip install twine
     4 |     ENTRYPOINT ["/opt/python/cp37-cp37m/bin/python", "/entrypoint.py"]
  --------------------
  ERROR: failed to solve: process "/bin/sh -c /opt/python/cp37-cp37m/bin/pip install twine" did not complete successfully: exit code: 1
Error: Docker build failed with exit code 1
```

- The error seems to be related to the installation of build dependencies using pip.
- The provided Dockerfile appears to fail at the specified line (`RUN /opt/python/cp37-cp37m/bin/pip install twine`).
- The notice suggests updating pip, but this does not resolve the issue.

Any guidance or insights into resolving this problem would be greatly appreciated.

Thank you!
